# CORRECTED Data Configuration for config/simplified/data_config.yaml
# Fixed coordinate order inconsistencies

data:
  # Paths
  root_dir: "data/processed"
  splits_dir: "data/splits"
  
  # Splits configuration
  splits:
    train: "train_files.txt"
    val: "val_files.txt"
    test: "test_files.txt"
  
  # Batch settings
  batch_size: 8
  num_workers: 2
  pin_memory: true
  persistent_workers: false
  
  # CRITICAL FIX: Corrected grid sizes to match actual data dimensions
  # All shapes follow [latitude, longitude] convention consistently
  domain:
    name: "odisha"
    # FIXED: All dimensions now follow [latitude, longitude] order
    grid_size_25km: [19, 26]        # CAPE: (lat=19, lon=26) ✅ 
    grid_size_3km: [181, 221]       # Lightning: (latitude=181, longitude=221) ✅
    grid_size_1km: [553, 660]       # Terrain: (lat=553, lon=660) ✅
  
  # Temporal settings
  temporal:
    sequence_length: 1
    temporal_stride: 1
    
  # Preprocessing
  preprocessing:
    normalize: true
    standardize: false
    cape_max_value: 5000.0
    terrain_max_value: 3000.0
    
  # Augmentation - disabled for debugging
  augmentation:
    spatial:
      enabled: false
    meteorological:
      enabled: false
  
  # CAPE Filtering Configuration
  cape_filtering:
    enabled: true
    threshold: 100.0              # CAPE threshold in J/kg  
    neighborhood_radius: 1        # 1 pixel = 25km radius
    background_sample_ratio: 0.05 # 5% background samples
    spatial_filtering: true       # Enable spatial analysis



# =============================================================================
# COORDINATE ORDER VERIFICATION:
# =============================================================================
# 
# Your actual data shapes:
# - CAPE: (time=744, lat=19, lon=26)
# - Lightning: (time=744, latitude=181, longitude=221)  
# - Terrain: (lat=553, lon=660)
#
# Geographic verification:
# - Odisha: 81.16-87.53°E (6.37° span), 17.76-22.63°N (4.87° span)
# - Longitude span > Latitude span ✓
# - More longitude points than latitude points ✓
#
# Config shapes now match data: [latitude, longitude]
# =============================================================================