# =============================================================================
# FILE 1: config/simplified/training_config.yaml
# =============================================================================

training:
  # Experiment
  experiment_name: "lightning_basic_learning_test"
  project_name: "lightning_prediction"
  seed: 42
  
  # Training Parameters
  max_epochs: 50
  patience: 15
  min_delta: 1e-5
  save_top_k: 3
  
  # Debug Configuration
  debug:
    enabled: true
    verbose_logging: true
    physics_debug: false
    cape_analysis: true
    memory_tracking: false
    metrics_debug: true
    batch_info: true
    save_debug_outputs: false
  
  # Optimizer
  optimizer:
    type: "AdamW"
    lr: 5e-4
    weight_decay: 1e-4
    
  # Scheduler
  scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.5
    patience: 5
    threshold: 1e-4
    
  # Loss Configuration - SIMPLIFIED
  loss:
    type: "simple"
    primary: "focal"
    physics_weight: 0.0
    focal_alpha: 0.5
    focal_gamma: 1.5
    label_smoothing: 0.0
    adaptive_weights: false
    adaptive_weighting: false
    
  # Domain Adaptation - DISABLED
  domain_adaptation:
    enabled: false
    
  # Hardware
  accelerator: "gpu"
  devices: 1
  precision: 32
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  log_every_n_steps: 50
  val_check_interval: 1.0
  deterministic: false

