# Data Configuration
data:
  # Paths
  root_dir: "data/processed"
  splits_dir: "data/splits"
  
  # Data Sources
  meteorological:
    cape:
      path: "meteorological/cape"
      resolution_km: 25
      variables: ["cape"]
      
    era5:  # Future
      path: "meteorological/era5"
      resolution_km: 25
      pressure_levels: [1000, 900, 800, 700, 600, 500, 400]
      variables: 
        - "u_wind"
        - "v_wind"
        - "vertical_velocity" 
        - "temperature"
        - "geopotential"
        - "specific_humidity"
        
  terrain:
    path: "terrain/terrain_odisha_1km.nc"
    resolution_km: 1
    variables: ["elevation"]
    
  lightning:
    path: "lightning"
    resolution_km: 3
    variables: ["lightning_occurrence"]
    
  # Domain Information
  domain:
    name: "odisha"
    grid_size_25km: [85, 85]
    grid_size_3km: [710, 710]
    grid_size_1km: [2130, 2130]
    
  # Temporal Information
  temporal:
    resolution: "hourly"
    sequence_length: 1
    
  # Data Loading
  batch_size: 1
  num_workers: 4
  pin_memory: true
  
  # Data Splits
  splits:
    train: "train_files.txt"
    val: "val_files.txt"
    test: "test_files.txt"
    
  # Augmentation - SIMPLE FORMAT
  augmentation:
    spatial:
      rotation: [-15, 15]
      flip_horizontal: 0.3
      flip_vertical: 0.3
    meteorological:
      noise_std: 0.005
      scale_factor: [0.98, 1.02]
