# Data Configuration
data:
  # Paths
  root_dir: "data/processed"
  splits_dir: "data/splits"
  
  # Data Sources
  meteorological:
    cape:
      path: "meteorological/cape"
      resolution_km: 25
      variables: ["cape"]
      
    era5:  # Future
      path: "meteorological/era5"
      resolution_km: 25
      pressure_levels: [1000, 900, 800, 700, 600, 500, 400]
      variables: 
        - "u_wind"
        - "v_wind"
        - "vertical_velocity" 
        - "temperature"
        - "geopotential"
        - "ice_water_content"
        - "liquid_water_content"
        - "water_vapor_content"
        - "specific_humidity"
        
  terrain:
    path: "terrain/terrain_odisha_1km.nc"
    resolution_km: 1
    variables: ["elevation"]
    
  lightning:
    path: "lightning"
    resolution_km: 3
    variables: ["lightning_occurrence"]
    
  # Domain Information. -- This is the domain information
  domain:
    name: "odisha"
    grid_size_25km: [19, 26]      # This comes from the ERA5 input
    grid_size_3km: [181, 221]     # SAME AS OBSERVATION DATA -- THIS IS ALSO THE GRID SIZE THE MODEL WILL GIVE ITS PREDICTION 
    grid_size_1km: [553, 660]
    

  # Temporal Information
  temporal:
    resolution: "hourly"
    sequence_length: 1
    
  # Data Loading
  batch_size: 16  # Keep at 1 for memory efficiency
  num_workers: 1 # Keep at 2
  pin_memory: true
  persistent_workers: false
  
  # Data Splits
  splits:
    train: "train_files.txt"
    val: "val_files.txt"
    test: "test_files.txt"
    
  # Augmentation
  augmentation:
    spatial:
      rotation: [-30, 30]
      flip_horizontal: 0.5
      flip_vertical: 0.5
    meteorological:
      noise_std: 0.01
      scale_factor: [0.95, 1.05]