# Model Configuration
model:
  name: "LightningPredictor"
  
  # Architecture Components
  encoders:
    cape:
      type: "CNN2D"
      channels: [16, 32, 64, 128]  # REDUCED from [32, 64, 128, 256]
      kernel_sizes: [7, 5, 3, 3]
      activation: "relu"
      dropout: 0.1
      
    era5:
      type: "CNN3D"
      in_channels: 9
      pressure_levels: 7
      channels: [16, 32, 64, 128]  # REDUCED from [32, 64, 128, 256]
      kernel_sizes: [3, 3, 3, 3]
      activation: "relu"
      dropout: 0.1
      
    terrain:
      type: "TerrainEncoder"
      embedding_dim: 48  # REDUCED from 64
      learnable_downsample: true
      downsample_method: "learned_conv"
      
  # Fusion Components
  fusion:
    meteorological:
      type: "FeatureFusion"
      fusion_method: "concatenation"
      hidden_dim: 256  # REDUCED from 512
      
    multiscale:
      type: "TerrainGuidedUpsampling"
      upsampling_factor: 8.33
      guidance_weight: 0.3
      
  # Core Processing - EfficientConvNet (Replacing GNN)
  gnn:  # Keep same config name for compatibility
    type: "EfficientConvNet"
    hidden_dim: 48  # REDUCED from 64
    num_layers: 2   # REDUCED from 3
    num_heads: 3    # REDUCED from 4
    dropout: 0.1
    # ConvNet-specific parameters
    kernel_sizes: [3, 5, 7]  # Keep same
    use_multiscale: true     # Keep same
    use_attention: true      # Keep same
    
  # Patch-Based Transformer with Adaptive Patch Size
  transformer:
    type: "PatchBasedTransformer"
    hidden_dim: 48  # REDUCED from 64
    num_layers: 2   # REDUCED from 3
    num_heads: 3    # REDUCED from 4
    dropout: 0.1
    attention_type: "linear"
    # Adaptive patch configuration for domain transfer
    target_patches_per_dim: 25  # Keep same
    max_patch_size: 32          # Keep same
    min_patch_size: 16          # Keep same
    
  # Output Head
  prediction_head:
    hidden_dim: 96  # REDUCED from 128
    output_dim: 1
    activation: "sigmoid"
    
  # Domain Adaptation
  domain_adapter:
    terrain_adaptation_dim: 48  # REDUCED from 64
    meteorological_adaptation_dim: 24  # REDUCED from 32
    dropout: 0.1