# Training Configuration
training:
  # Experiment
  experiment_name: "cape_enhanced_physics_v1"
  project_name: "lightning_prediction"
  
  # Training Parameters
  max_epochs: 100
  patience: 15
  min_delta: 1e-4
  
  # Optimizer
  optimizer:
    type: "AdamW"
    lr: 1e-5  # Keep same - reduced learning rate from 1e-4 to 1e-5
    weight_decay: 1e-5
    
  # Scheduler
  scheduler:
    type: "CosineAnnealingWarmRestarts"
    T_0: 50
    T_mult: 2
    eta_min: 1e-6
    
  # Loss Configuration - ENHANCED with new physics constraints
  loss:
    type: "composite"
    primary: "focal"
    
    # Main physics weight (overall scaling)
    physics_weight: 0.15  # INCREASED from 0.02 to give physics more influence
    
    # Individual physics constraint weights
    charge_separation_weight: 0.08  # INCREASED from 0.01 - main CAPE physics
    microphysics_weight: 0.01       # Keep same - will be zero without temperature data
    terrain_consistency_weight: 0.01  # INCREASED from 0.005 - terrain effects
    
    # NEW: Additional CAPE-specific physics weights
    cape_gradient_weight: 0.03      # NEW - CAPE gradient/convergence zone physics
    cape_temporal_weight: 0.02      # NEW - temporal CAPE consistency (future use)
    
    # Focal loss parameters
    focal_alpha: 0.25
    focal_gamma: 2.0
    label_smoothing: 0.0
    
    # Adaptive learning settings
    adaptive_weights: true          # Keep same - adaptive tuning enabled
    adaptive_weighting: true        # Keep same - adaptive main/physics balance
    
  # Hardware
  accelerator: "gpu"
  devices: 1
  precision: 32  # Keep same - maintain precision 32
  
  # Memory Optimization
  gradient_accumulation_steps: 4  # Keep same for now
  max_grad_norm: 1.0
  
  # Reproducibility
  seed: 42
  deterministic: false  # Keep same - disabled to avoid CUDA issues
  
  # Logging
  log_every_n_steps: 50
  val_check_interval: 1.0
  
  # Checkpointing
  save_top_k: 3
  save_last: true
  monitor: "val_f1_score"
  mode: "max"
  
  # Domain Adaptation
  domain_adaptation:
    enabled: true
    adaptation_layers: ["terrain", "meteorological"]
    warmup_epochs: 10  # Added explicit warmup setting
  
  # CAPE Physics Configuration - NEW SECTION
  cape_physics:
    # Multi-threshold CAPE settings
    thresholds:
      no_lightning: 1000.0      # Below this: strongly discourage lightning
      moderate: 2500.0          # 1000-2500: moderate lightning probability
      high: 4000.0              # 2500-4000: high lightning probability  
      saturation: 5000.0        # Above this: potential saturation effects
    
    # Gradient detection settings
    gradient:
      weight: 0.1               # Weight for gradient constraint within charge separation
      threshold: 500.0          # CAPE gradient threshold (J/kg per grid cell)
    
    # Saturation physics settings
    saturation:
      weight: 0.05              # Weight for saturation constraint
      optimal_cape: 3500.0      # Optimal CAPE value for lightning (J/kg)
  
  # Debug Configuration
  debug:
    enabled: true              # Master debug switch - set to true to enable all debug output
    verbose_logging: true      # Detailed logging throughout the pipeline
    memory_tracking: false     # Memory checkpoint tracing and monitoring
    metrics_debug: false       # Debug prints in metrics calculations
    batch_info: true          # Batch shape and content information
    save_debug_outputs: false  # Save intermediate outputs for inspection
    
    # NEW: Physics debugging
    physics_debug: true        # Debug physics constraint calculations
    cape_analysis: true        # Log CAPE statistics and distributions