# Training Configuration
training:
  # Experiment
  experiment_name: "cape_auto_balance_v1"
  project_name: "lightning_prediction"
  
  # Training Parameters
  max_epochs: 100
  patience: 25
  min_delta: 1e-4
  
  # Debug Configuration - NEW SECTION
  debug:
    enabled: false                    # Master debug switch
    verbose_logging: false            # Detailed logging and prediction analysis
    physics_debug: false              # Physics constraint debugging
    cape_analysis: false              # CAPE data distribution analysis
    memory_tracking: false           # Memory usage tracking (can be heavy)
    metrics_debug: false             # Detailed metrics debugging
    batch_info: false                 # Batch-level information
    save_debug_outputs: false        # Save debug files to disk
  
  # Optimizer
  optimizer:
    type: "AdamW"
    lr: 1e-5
    weight_decay: 1e-5
    
  # Scheduler
  scheduler:
    type: "CosineAnnealingWarmRestarts"
    T_0: 20
    T_mult: 2
    eta_min: 5e-7
    
  # Loss Configuration
  loss:
    type: "composite"
    primary: "focal"
    
    # --- NEW: Automatic Loss Balancing Control ---
    # Set to true to enable uncertainty-based automatic loss balancing.
    # The model will learn to balance the convection and lightning losses itself.
    automatic_balancing: true

    # This weight is ONLY used if automatic_balancing is set to false.
    # Total Loss = (1 - weight) * LightningLoss + weight * ConvectionLoss
    convection_loss_weight: 0.3
    
    # Main physics weight (overall scaling)
    physics_weight: 0.01
    
    # Individual physics constraint weights
    charge_separation_weight: 0.03
    microphysics_weight: 0.01
    terrain_consistency_weight: 0.01
    
    # NEW: Additional CAPE-specific physics weights
    cape_gradient_weight: 0.03
    cape_temporal_weight: 0.02
    
    # Focal loss parameters
    focal_alpha: 0.8
    focal_gamma: 2.0
    label_smoothing: 0.0
    
    # Adaptive learning settings
    adaptive_weights: true
    adaptive_weighting: true
    
  # Hardware
  accelerator: "gpu"
  devices: 1
  precision: 32
  
  # Memory Optimization
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  
  # Reproducibility
  seed: 42
  deterministic: false
  
  # Logging
  log_every_n_steps: 50
  val_check_interval: 1.0
  
  # Checkpointing
  save_top_k: 3
  save_last: true
  monitor: "val_average_precision"
  mode: "max"
  
  # Domain Adaptation
  domain_adaptation:
    enabled: true
    adaptation_layers: ["terrain", "meteorological"]
    warmup_epochs: 10
  
  # CAPE Physics Configuration - NEW SECTION
  cape_physics:
    thresholds:
      no_lightning: 1000.0
      moderate: 2500.0
      high: 4000.0
      saturation: 5000.0
    
    saturation:
      optimal_cape: 3500.0
      saturation_factor: 0.1
    
    gradient:
      convergence_threshold: 500.0
      enhancement_factor: 1.5
